// Auto-generated by scripts/generate-release-notes.mjs
// This file is overwritten in GitHub release workflow builds.
export const RELEASE_NOTES: { version: string; markdown: string } = {
  "version": "0.8.2",
  "markdown": "test"
};
