// Auto-generated by scripts/generate-release-notes.mjs
// This file is overwritten in GitHub release workflow builds.
export type ReleaseNotesEntry = {
  version: string;
  markdown: string;
};

export const RELEASE_NOTES_LOG: ReleaseNotesEntry[] = [
  {
    version: "0.8.3",
    markdown: `- Add a versioned bundled release-notes log and show all changes between the previously seen plugin version and the current version.
- Add a manual **Maintenance -> Release Notes -> Show** button to reopen the **What's New** splash on demand.
- Strip per-release \`Full Changelog:\` lines from bundled notes and show one canonical link to the full changelog in the splash footer.
- Improve release-note bundling by merging GitHub Release notes history (with local fallback) into the generated \`releaseNotes.ts\` log.`,
  },
  {
    version: "0.8.2",
    markdown: `- Generate bundled **What's New** content automatically from the GitHub Release body during the release workflow.
- Render **What's New** content as Markdown so release notes formatting is preserved.
- Store only the current release's bundled notes instead of maintaining a full in-repo version history map.
- Package cleanup:
  - exclude \`.DS_Store\` from release archives,
  - remove tracked Python \`__pycache__\` artifacts,
  - remove obsolete root \`ocr_wordlist.txt\`.`,
  },
  {
    version: "0.8.1",
    markdown:
      "- Add an automatic **What's New** splash modal shown once after plugin version updates, backed by bundled versioned release notes.",
  },
  {
    version: "0.8.0",
    markdown: `- Add optional **agentic retrieval** mode with a lightweight planner step before answer generation.
- Add agentic retrieval actions:
  - keep current context,
  - run an expansion retry retrieval pass,
  - pull full-document chunks for whole-document synthesis queries.
- Add agentic controls in settings (\`Enable agentic retrieval\`, \`Agentic max iterations\`).
- Extend RAG tool output with \`agentic_mode\` and \`agentic_trace\` for debugging and tuning.
- Add an animated **Thinking** indicator in the assistant bubble before streaming starts.
- Update docs for retrieval tuning and chat panel behavior.`,
  },
  {
    version: "0.7.0",
    markdown: `- Add Python worker runtime architecture as the recommended path, with Redis and Python running as separate compose services.
- Route Python execution through the worker container in worker mode, including path mapping, worker readiness checks, and worker startup helpers.
- Improve worker reliability:
  - fix requirements path resolution and add fallback handling in worker entrypoint,
  - rebuild worker image automatically on worker startup,
  - remove home-directory mount to avoid Docker home-sharing prompts.
- Improve worker networking compatibility by mapping local loopback provider URLs for container execution.
- Add configurable Tesseract language pack installation in the worker image (default: \`eng deu fra spa ita nld por pol swe\`).
- Keep local Python fallback mode while disabling/greying local-only Python settings when worker runtime is selected.
- Update docs for worker-first setup, OCR dependencies, Docker setup, and troubleshooting.
- PDF sidebar sync stability fixes:
  - serialize/queue sidebar PDF page jumps and retry once on PDF.js \`injectLinkAnnotations\` render-order race,
  - stop forcing active-leaf switching during sidebar sync to avoid triggering incompatible active-leaf handlers in other plugins.`,
  },
];
